schema: schema.graphql
extensions:
  endpoints:
    Gatsby GraphQL Endpoint:
      url: http://localhost:3001/graphql
      headers:
        user-agent: JS GraphQL
        Content-Type: application/json
      introspect: true
